package developerhub

import (
	"context"
	"fmt"
)

const applicationsPath = "/odata/1.0/data.svc/APIMgmt.Applications"

// placeholderID is the all-zero 32-character key SAP's own documentation
// samples always send in the "id" field of a create payload (both for
// APIMgmt.Applications and APIMgmt.Subscriptions - see
// create-or-update-or-read-an-application-using-subscription-key-e2645b5.md,
// DESIGN.md §5). The entity's "id" property is declared Nullable="false" in
// SAP's own EDMX, and every documented create example includes this exact
// placeholder rather than omitting the field, so this client does the same
// rather than risk relying on omission being accepted.
const placeholderID = "00000000000000000000000000000000"

// Application is a Developer Hub application, as modeled by the
// "APIMgmt.Applications" OData entity documented in DESIGN.md §5
// (custom-attributes-90a5a6d.md, add-custom-attributes-to-an-application-39c3cbd.md,
// create-or-update-or-read-an-application-using-subscription-key-e2645b5.md).
// Field names and casing are those of "developer.ApplicationsType" in the
// DevPortal_Application_CF specification (api-specs/), which also confirms
// SAP's earlier Help Portal samples.
type Application struct {
	ID          string `json:"id,omitempty"`
	Version     string `json:"version,omitempty"`
	Title       string `json:"title"`
	Description string `json:"description,omitempty"`
	ShortText   string `json:"shortText,omitempty"`
	CallbackURL string `json:"callbackurl,omitempty"`
	DeveloperID string `json:"developer_id,omitempty"`
	// AppKey and AppSecret are generated by SAP and returned only in the
	// response to Create. A documented GET of an application "will not
	// fetch app key and secret" (same doc), so these are never populated
	// by GetApplication.
	AppKey    string `json:"app_key,omitempty"`
	AppSecret string `json:"app_secret,omitempty"`
}

// CreateApplication creates a new Developer Hub application and returns it
// with the server-assigned id, app_key and app_secret populated.
func (c *Client) CreateApplication(ctx context.Context, app Application) (*Application, error) {
	app.ID = placeholderID
	var created Application
	if err := c.post(ctx, applicationsPath, app, &created); err != nil {
		return nil, err
	}
	return &created, nil
}

// GetApplication reads a single application by its SAP-assigned id. It does
// not return app_key/app_secret (SAP does not echo them back on read - see
// the Application type doc comment); its custom attributes are read
// separately via ListApplicationAttributes (attributes.go), and its
// subscriptions via the top-level Subscriptions entity set
// (subscriptions.go), which - unlike this file's comment previously
// assumed - is not a per-application navigation collection but its own
// addressable entity set with app_id as a plain field (DESIGN.md §9).
func (c *Client) GetApplication(ctx context.Context, id string) (*Application, error) {
	path := fmt.Sprintf("%s(%s)", applicationsPath, odataKey(id))
	var app Application
	if err := c.get(ctx, path, &app); err != nil {
		return nil, err
	}
	return &app, nil
}

// UpdateApplication updates the mutable fields of an existing application.
func (c *Client) UpdateApplication(ctx context.Context, id string, app Application) error {
	path := fmt.Sprintf("%s(%s)", applicationsPath, odataKey(id))
	return c.put(ctx, path, app)
}

// DeleteApplication deletes an application by id.
func (c *Client) DeleteApplication(ctx context.Context, id string) error {
	path := fmt.Sprintf("%s(%s)", applicationsPath, odataKey(id))
	return c.delete(ctx, path)
}

// ListApplications reads every application via
// "GET .../APIMgmt.Applications", documented in
// create-or-update-or-read-an-application-using-subscription-key-e2645b5.md.
// Per that document the collection read does not return app_key/app_secret.
func (c *Client) ListApplications(ctx context.Context) ([]Application, error) {
	return listAll[Application](ctx, c, applicationsPath)
}
